apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-backend
  namespace: chat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-backend
  template:
    metadata:
      labels:
        app: chat-backend
    spec:
      containers:
        - name: backend
          # Updated to point to AWS ECR
          image: 483528439431.dkr.ecr.ap-south-1.amazonaws.com/chat-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: chat-config
            - secretRef:
                name: chat-secret