apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-frontend
  namespace: chat-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chat-frontend
  template:
    metadata:
      labels:
        app: chat-frontend
    spec:
      containers:
        - name: frontend
          # Updated to point to AWS ECR
          image: 483528439431.dkr.ecr.ap-south-1.amazonaws.com/chat-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80